//CARGAR OS

var os_1 = ["SELECCIONE OS","ASOCIART ART","BERKLEY ART","CAJA DE ABOG","COOP. MEDICA RIO IV","DASUTEN",
            "MEDICAMENTO PRIMER NIVEL","EXPERIENCIA ART","EXPERTA ART","GALENO ART","LA SEGUNDA ART",
            "LIBERTY ART","LIDERAR ART","PLUS ART","OMINT ART","JERARQUICOS SALUD","O.S.A.P.M",
            "OSDEPYM","OSBA","OSDIPP","O.S. PERS. DE FCIAS.","OS.S FEDERACIÓN DE LA CARNE",
            "ORG. ROCA","OSIAD ACEITEROS (FCIAS.AUTORIZADAS)","OSPIC CAUCHO","OSPIT TEXTILES",
            "OSPIP PLÁSTICOS","OSMATA","OSFATLYF","OSFE (OBRA SOCIAL FERROVIARIA )","PODER JUDICIAL",
            "POLICÍA FEDERAL MES ACTUAL","POLICÍA FEDERAL MESES ANTERIORES",
            "POLICIA FEDERAL TRAT ESPECIALES (FCIAS AUT)","PROVINCIA ART",
            "RECETARIO SOLIDARIO 1ºQ JULIO","SIPSSA PREPAGO (PREFIJO 31)","SIPSSA OSPOCE (PREFIJO 29)",
            "SIPSSA OSPOCE APEX (PREFIJO 35)","SIPSSA OSCEP (PREFIJO 32)","SIPSSA ASSPE (PREFIJO 33)",
            "SIPSSA OSIM (PREFIJO 22)","SIPSSA APM (PREFIJO 34)","SIPSSA TA (PREFIJO 36)",
            "SIPSSA PLAN 37 EMPLEADOS","SANCOR SEGUROS INTEGROS","SERVIRED","SWISS MEDICAL VALIDADAS",
            "SWISS MEDICAL NO VALIDADAS","SWISS MEDICAL ART","UNIÓN PERSONAL","VICTORIA ART"];
            
cargar_os = (param) => {
    let select = document.createElement("select");
    param.appendChild(select);
    select.setAttribute("class","form-select")
    for (let i = 0; i < os_1.length; i++) {
        let option = document.createElement("option");
        select.appendChild(option);
        option.innerHTML = os_1[i];        
    }
}   


//CARGAR PLANES
var plan_ASOCIART = "AMB.";
var plan_BERKLEY = "AMB.";
var plan_ABOG = ["AMB.","PMI. 100%","ESPECIALES"];
var plan_MEDICA_RIO_IV = ["AMB. 40%","AMB 50%","PMI","CRÓNICOS (40,50%)"];
var plan_DASUTEN = ["AMB. MIXTO","ANTICONCEP. 100%","ACCID. DE TRABAJO","PMI 100%"];
var plan_MEDICAMENTO_PRIMER_NIVEL = "AMB.";
var plan_EXPERIENCIA_ART = "AMB.";
var plan_EXPERTA_ART = "AMB.";
var plan_GALENO_ART = "AMB.";
var plan_LA_SEGUNDA_ART = "AMB.";
var plan_LIBERTY_ART = "AMB.";
var plan_LIDERAR_ART = "AMB.";
var plan_PLUS_ART = "AMB.";
var plan_OMINT_ART = "AMB.";
var plan_JERARQUICOS_SALUD = "SUMA DE PLANES";
var plan_OSAPM = ["AMB.","CRON.","PMI","DISCAPACIDAD"];
var plan_OSDEPYM = ["40%","50%","M. F - 70% -100%","PMI"];
var plan_OSBA = "SUMA DE PLANES";
var plan_OSDIPP = "SUMA DE PLANES";
var plan_OS_PERS_DE_FCIAS = ["AMB.","PMI"];
var plan_OS_S_FEDERACIÓN_DE_LA_CARNE = "AMB 50%";
var plan_ORG_ROCA = "AMB.";
var plan_OSIAD_ACEITEROS = ["AMB 40%","CRON 70%","ANTICONCEPTIVOS","PMI 100%"];
var plan_OSPIC_CAUCHO = "AMB.";
var plan_OSPIT_TEXTILES = "TOTAL";
var plan_OSPIP_PLÁSTICOS = "SUMA DE PLANES";
var plan_OSMATA = "SUMA DE PLANES";
var plan_OSFATLYF = ["BASICO 40%","ESP.-ADHER 50%","PMI ONLINE","ANTICONCEPTIVOS","CRON 70-100%","VARIOS-MIXTOS","AUTORIZACIONES"];
var plan_OSFE = ["AMB. 40%","PMI 100%","AUT. ESP."];
var plan_PODER_JUDICIAL = "SUMA DE PLANES";
var plan_POLICIA_FEDERAL_MES_ACTUAL = ["ACTIVOS 50%","ACTIVOS 100%","PASIVOS 50%","PASIVOS 100%","PMI"];
var plan_POLICÍA_FEDERAL_MESES_ANTERIORES = ["ACTIVOS 50%","ACTIVOS 100%","PASIVOS 50%","PASIVOS 100%","PMI"];
var plan_POLICIA_FEDERAL_TRAT_ESPECIALES = "TRAT. ESPECIALES";
var plan_PROVINCIA_ART  = "AMB";
var plan_RECETARIO_SOLIDARIO = "VALIDADAS";
var plan_SIPSSA_PREPAGO = ["AMB 40%","AMB 50%","AUT. ESP."];
var plan_SIPSSA_OSPOCE = ["AMB 40%","AMB 50%","AUT. ESP."];
var plan_SIPSSA_OSPOCE_APEX = ["AMB 40%","AMB 50%","AUT. ESP."];
var plan_SIPSSA_OSCEP = ["AMB 40%","AMB 50%","AUT. ESP."];
var plan_SIPSSA_ASSP = ["AMB 40%","AMB 50%","AUT. ESP."];
var plan_SIPSSA_OSIM = ["AMB 40%","AMB 50%","AUT. ESP."];
var plan_SIPSSA_APM = ["AMB 40%","AMB 50%","AUT. ESP."];
var plan_SIPSSA_TA = ["AMB 40%","AMB 50%","AUT. ESP."];
var plan_SIPSSA_PLAN_37_EMPLEADOS = ["AMB 40%","AMB 50%","AUT. ESP."];
var plan_SANCOR_SEGUROS_INTEGROS  = "AMB";
var plan_SERVIRED = ["AMB. 40%/50%","CRON. 70%/100%","PMI "];
var plan_SWISS_MEDICAL_VALIDADAS = "SUMA DE PLANES";
var plan_SWISS_MEDICAL_NO_VALIDADAS = ["AMB 40%","PMI 100%","AUT 100%"];
var plan_SWISS_MEDICAL_ART = "AMB";
var plan_UNIÓN_PERSONAL = ["SUMA DE PLANES","20%"];
var plan_VICTORIA_ART = "AMB";